# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maria Kat
tagline:          ''
description:      'nothing stays.'
url:
baseurl:          "/"

author:
  name:           'Maria Kat'
  url:

paginate:         5

# Build settings
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

colors:
    cyan:       theme-base-0c
    orange:     theme-base-09
    blue:       theme-base-0d
    magenta:    theme-base-0e

# Custom vars
version:          2.1.0

socialmedia:
    github:     https://github.com/mariakatsourani
    linkedin:   https://www.linkedin.com/in/mariakatsourani
    email:      maria.katsourani@outlook.com
